#!/usr/bin/env bash
#script that displays a, infinity and beyond indefinitely

trap 'echo "I am invincible!!!"' SIGTERM

while :
do
	for ((i=0; ; i++))
	do
		echo "To infinity and beyond"
		sleep 2
	done
done
