#!/usr/bin/env bash
# Display "Best School" using while loop.

# On the 9th iteration, displays, "Hi" Before "Best School".

count=0

while [ $count -lt 10 ]
do
        if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	((count++))
done
