#!/usr/bin/env bash
# display the content of the current directory inlist format
# only display the part of the name after the first dash

list=$(ls)
for i in $list; do
        echo "$i" | cut -d '-' -f2
done
